import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const tools = process.argv[2] === "tools";

const external = [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
];

// The analysis tool runs in Node, so only its own graph code is bundled: the
// Obsidian API is not part of the graph layer.
if (tools) {
    // Obsidian API тут не нужен: вместо него заглушка с нормализацией пути.
    const shared = {
        bundle: true,
        platform: "node",
        alias: { obsidian: "./tools/obsidian-stub.ts" },
        // Браузерные имена подставляются, а не пишутся в глобальный объект.
        inject: ["./tools/browser.ts"],
        format: "esm",
        target: "node20",
        logLevel: "warning",
        treeShaking: true,
    };
    await esbuild.build({ ...shared, entryPoints: ["tools/vault-report.ts"], outfile: ".cache/tools/vault-report.mjs" });
    await esbuild.build({ ...shared, entryPoints: ["tools/graph-cases.ts"], outfile: ".cache/tools/graph-cases.mjs" });
    await esbuild.build({ ...shared, entryPoints: ["tools/settings-cases.ts"], outfile: ".cache/tools/settings-cases.mjs" });
    await esbuild.build({ ...shared, entryPoints: ["tools/plugin-cases.ts"], outfile: ".cache/tools/plugin-cases.mjs" });
    process.exit(0);
}

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external,
    format: "cjs",
    target: "es2021",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
